### ISSUE TITLE
Fix: Do not uninstall all types_not_searched

### ISSUE THREAD

**Issue by busykoala** [4teamwork/ftw.collectionblock#19]
Uninstalling like below will pass in tests but also remove all types_not_searched once this package is uninstalled (also from other packages).

https://github.com/4teamwork/ftw.collectionblock/blob/1aad310bd88421ad7d4ef075d528d07201ecf154/ftw/collectionblock/profiles/uninstall_plone5/registry.xml#L3

The desired effect can be achieved using a hook:
https://github.com/4teamwork/ftw.book/blob/cd27d19884122d51ee23b8396800291b77d500f5/ftw/book/hooks.py#L27-L32

**Comment by maethu** [comment]
Max: 4h (Auf Team Plone / OGB -> Entwicklung rapportieren)

**Comment by maethu** [comment]
Please consider feedback in PR
