### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by tinagerber** [4teamwork/ftw.collectionblock#21]
If test page and page 2 are not created in the same minute, the test fails because the wrong date is compared.

https://github.com/4teamwork/ftw.collectionblock/blob/1aad310bd88421ad7d4ef075d528d07201ecf154/ftw/collectionblock/tests/test_add_collecionblock.py#L162-L184

**Comment by jone** [comment]
@tinagerber could you fix that by using the [freezer](https://github.com/4teamwork/ftw.testing#freezing-datetime-now) ?
